const ERROR_CODE_BAD_REQUEST = 400;

const ERROR_CODE_NOT_FOUND = 404;

const ERROR_CODE_INTERNAL_SERVER = 500;

const STATUS_CODE_CREATED = 201;

const STATUS_CODE_SUCCESS = 200;

module.exports = {
  ERROR_CODE_BAD_REQUEST,
  ERROR_CODE_NOT_FOUND,
  ERROR_CODE_INTERNAL_SERVER,
  STATUS_CODE_CREATED,
  STATUS_CODE_SUCCESS,
};
